defaults:
  - _self_

dataset:
  name: mnist
  batch_size: 64

optimizer:
  name: adam
  lr: 0.001
  betas: [0.9, 0.999]
  eps: 1e-8

hydra:
  run:
    dir: /home/yyf/learning_tools/hydra/outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: /home/yyf/learning_tools/hydra/multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
